---
  parser: babel-eslint
  parserOptions:
    experimentalObjectRestSpread: true
  plugins:
    - react
  env:
    es6: true
    browser: true
  extends:
    - plugin:react/recommended
    - airbnb
  rules:

    # personal preference
    space-before-function-paren:
      - error
      - never
    consistent-return:
      - off

    # react-router
    jsx-a11y/anchor-is-valid:
      - error
      - specialLink:
        - to
    react/prop-types:
      - warn #TEMP
      - ignore:
        - children
        - location
        - history
        - match

    # Dan Abramov says so: https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904
    react/jsx-filename-extension:
      - error
      - extensions:
        - .js

    # sometimes it's really optional, do I need to specify default null?
    react/require-default-props:
      - off

    # nbd and switching back/forth is slow early on
    react/prefer-stateless-function:
      - off #TEMP

  overrides:
    - files:
        - src/**/*.test.js
        - src/**/*.test.jsx
        - src/setupTests.js
      env:
        mocha: true
      globals:
        expect: true
      rules:
        prefer-arrow-callback: off
        func-names: off
        import/no-extraneous-dependencies:
          - error
          - devDependencies: true
